-- 0. Drop old exercises table if it exists (from legacy schema)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'exercises' AND table_schema = 'public') THEN
    DROP TABLE public.exercises CASCADE;
  END IF;
END $$;

-- Migration: Create Exercise Widget Data Model (comprehensive, expandable)
-- Date: 2024-05-17

-- 1. Create workout_sessions table
CREATE TABLE public.workout_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  duration INT,
  notes TEXT,
  perceived_difficulty INT,
  type TEXT NOT NULL CHECK (type IN ('strength', 'cardio', 'mixed')),
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

COMMENT ON TABLE public.workout_sessions IS 'Represents a single workout event for a user.';
COMMENT ON COLUMN public.workout_sessions.user_id IS 'Foreign key referencing the user.';
COMMENT ON COLUMN public.workout_sessions.perceived_difficulty IS 'User-reported difficulty (e.g., RPE scale).';
COMMENT ON COLUMN public.workout_sessions.type IS 'Type of workout: strength, cardio, or mixed.';

-- 2. Create exercises table (catalog)
CREATE TABLE public.exercises (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL CHECK (category IN ('strength', 'cardio')),
  default_unit TEXT,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

COMMENT ON TABLE public.exercises IS 'Catalog of exercise types.';
COMMENT ON COLUMN public.exercises.category IS 'Exercise category: strength or cardio.';

-- 3. Create workout_exercises table (join session <-> exercise)
CREATE TABLE public.workout_exercises (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL REFERENCES public.workout_sessions(id) ON DELETE CASCADE,
  exercise_id BIGINT NOT NULL REFERENCES public.exercises(id),
  "order" INT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

COMMENT ON TABLE public.workout_exercises IS 'Exercises performed in a workout session.';

-- 4. Create sets table (for strength exercises)
CREATE TABLE public.sets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workout_exercise_id BIGINT NOT NULL REFERENCES public.workout_exercises(id) ON DELETE CASCADE,
  set_number INT NOT NULL,
  reps INT,
  weight NUMERIC,
  rir INT, -- Reps in reserve
  tempo TEXT,
  rest_seconds INT,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

COMMENT ON TABLE public.sets IS 'Tracks sets for strength exercises.';

-- 5. Create cardio_metrics table (for cardio exercises)
CREATE TABLE public.cardio_metrics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workout_exercise_id BIGINT NOT NULL REFERENCES public.workout_exercises(id) ON DELETE CASCADE,
  distance NUMERIC,
  duration INT,
  calories INT,
  avg_hr INT,
  max_hr INT,
  intensity TEXT,
  pace NUMERIC,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

COMMENT ON TABLE public.cardio_metrics IS 'Metrics for cardio exercises.';

-- 6. Create exercise_tags table
CREATE TABLE public.exercise_tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exercise_id BIGINT NOT NULL REFERENCES public.exercises(id) ON DELETE CASCADE,
  tag TEXT NOT NULL
);

COMMENT ON TABLE public.exercise_tags IS 'Tags for exercises (e.g., muscle group, equipment).';

-- 7. Indexes for user_id and foreign keys
CREATE INDEX idx_workout_sessions_user_id ON public.workout_sessions(user_id);
CREATE INDEX idx_workout_exercises_session_id ON public.workout_exercises(session_id);
CREATE INDEX idx_workout_exercises_exercise_id ON public.workout_exercises(exercise_id);
CREATE INDEX idx_sets_workout_exercise_id ON public.sets(workout_exercise_id);
CREATE INDEX idx_cardio_metrics_workout_exercise_id ON public.cardio_metrics(workout_exercise_id);
CREATE INDEX idx_exercise_tags_exercise_id ON public.exercise_tags(exercise_id);

-- 8. Add comments for clarity (already included above)

-- 9. Enable Row Level Security (RLS) for workout_sessions
ALTER TABLE public.workout_sessions ENABLE ROW LEVEL SECURITY;

-- 10. RLS policies for workout_sessions (users can only access their own)
CREATE POLICY "Allow users to select their own workout_sessions"
  ON public.workout_sessions
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Allow users to insert their own workout_sessions"
  ON public.workout_sessions
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow users to update their own workout_sessions"
  ON public.workout_sessions
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- 11. Triggers for updated_at
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_workout_sessions_updated
  BEFORE UPDATE ON public.workout_sessions
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_updated_at();

-- 12. (Optional) Add RLS to other tables as needed for user isolation
-- (e.g., workout_exercises, sets, cardio_metrics) if they store user_id directly in future

-- 13. (Optional) Add unique constraints or additional indexes as needed
-- (e.g., unique (user_id, date) on workout_sessions for one session per day) 