-- Migration: Create Guitar Practice Widget Data Model (comprehensive, expandable)
-- Date: 2024-05-18

-- 0. Drop old guitar_practice table if it exists
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'guitar_practice' AND table_schema = 'public') THEN
    DROP TABLE public.guitar_practice CASCADE;
  END IF;
END $$;

-- 1. Practice Sessions
CREATE TABLE public.guitar_practice_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  duration INT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);
COMMENT ON TABLE public.guitar_practice_sessions IS 'Represents a single guitar practice session.';

-- 2. Techniques Catalog
CREATE TABLE public.guitar_techniques (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT,
  difficulty_level TEXT,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);
COMMENT ON TABLE public.guitar_techniques IS 'Catalog of guitar techniques (e.g., alternate picking, sweep picking, chords).';

-- 3. Songs/Pieces Catalog
CREATE TABLE public.guitar_songs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  artist TEXT,
  difficulty_level TEXT,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);
COMMENT ON TABLE public.guitar_songs IS 'Catalog of songs or pieces practiced.';

-- 4. Skills Catalog
CREATE TABLE public.guitar_skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);
COMMENT ON TABLE public.guitar_skills IS 'Catalog of skill categories (e.g., rhythm, lead, improvisation).';

-- 5. Join Table: Techniques practiced in a session
CREATE TABLE public.guitar_session_techniques (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL REFERENCES public.guitar_practice_sessions(id) ON DELETE CASCADE,
  technique_id BIGINT NOT NULL REFERENCES public.guitar_techniques(id),
  skill_id BIGINT REFERENCES public.guitar_skills(id),
  notes TEXT,
  duration INT,
  proficiency_level TEXT,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);
COMMENT ON TABLE public.guitar_session_techniques IS 'Techniques practiced in a session, with optional skill and proficiency.';

-- 6. Join Table: Songs practiced in a session
CREATE TABLE public.guitar_session_songs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL REFERENCES public.guitar_practice_sessions(id) ON DELETE CASCADE,
  song_id BIGINT NOT NULL REFERENCES public.guitar_songs(id),
  notes TEXT,
  duration INT,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);
COMMENT ON TABLE public.guitar_session_songs IS 'Songs practiced in a session.';

-- 7. Skill Progress Tracking
CREATE TABLE public.guitar_skill_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  skill_id BIGINT NOT NULL REFERENCES public.guitar_skills(id),
  date DATE NOT NULL,
  proficiency_level TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);
COMMENT ON TABLE public.guitar_skill_progress IS 'Tracks user skill progression over time.';

-- 8. Indexes
CREATE INDEX idx_guitar_practice_sessions_user_id ON public.guitar_practice_sessions(user_id);
CREATE INDEX idx_guitar_session_techniques_session_id ON public.guitar_session_techniques(session_id);
CREATE INDEX idx_guitar_session_techniques_technique_id ON public.guitar_session_techniques(technique_id);
CREATE INDEX idx_guitar_session_songs_session_id ON public.guitar_session_songs(session_id);
CREATE INDEX idx_guitar_session_songs_song_id ON public.guitar_session_songs(song_id);
CREATE INDEX idx_guitar_skill_progress_user_id ON public.guitar_skill_progress(user_id);
CREATE INDEX idx_guitar_skill_progress_skill_id ON public.guitar_skill_progress(skill_id);

-- 9. Comments and future expansion
-- Add tags, audio logs, or proficiency rubrics as needed in future migrations.

-- 10. Row Level Security (RLS) and Policies
-- Enable RLS and add policies for user-specific tables
ALTER TABLE public.guitar_practice_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.guitar_skill_progress ENABLE ROW LEVEL SECURITY;

-- RLS for guitar_practice_sessions
CREATE POLICY "Allow users to select their own practice sessions"
  ON public.guitar_practice_sessions
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Allow users to insert their own practice sessions"
  ON public.guitar_practice_sessions
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow users to update their own practice sessions"
  ON public.guitar_practice_sessions
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- RLS for guitar_skill_progress
CREATE POLICY "Allow users to select their own skill progress"
  ON public.guitar_skill_progress
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Allow users to insert their own skill progress"
  ON public.guitar_skill_progress
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow users to update their own skill progress"
  ON public.guitar_skill_progress
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- RLS for join tables: allow access if the parent session belongs to the user
ALTER TABLE public.guitar_session_techniques ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow users to access their own session techniques"
  ON public.guitar_session_techniques
  FOR ALL
  USING (EXISTS (
    SELECT 1 FROM public.guitar_practice_sessions s
    WHERE s.id = session_id AND s.user_id = auth.uid()
  ));

ALTER TABLE public.guitar_session_songs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow users to access their own session songs"
  ON public.guitar_session_songs
  FOR ALL
  USING (EXISTS (
    SELECT 1 FROM public.guitar_practice_sessions s
    WHERE s.id = session_id AND s.user_id = auth.uid()
  ));

-- 11. Trigger for updated_at on guitar_practice_sessions
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_guitar_practice_sessions_updated
  BEFORE UPDATE ON public.guitar_practice_sessions
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_updated_at(); 