-- 1. Create the dashboard_layouts table
CREATE TABLE public.dashboard_layouts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  layout_name TEXT NOT NULL DEFAULT 'default',
  layout_data JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- 2. Add comments to the table and columns for clarity
COMMENT ON TABLE public.dashboard_layouts IS 'Stores user-specific dashboard layout configurations.';
COMMENT ON COLUMN public.dashboard_layouts.user_id IS 'Foreign key referencing the user associated with this layout.';
COMMENT ON COLUMN public.dashboard_layouts.layout_name IS 'Name of the layout (e.g., "default", "work"). Allows for multiple layouts per user in the future.';
COMMENT ON COLUMN public.dashboard_layouts.layout_data IS 'JSON object containing the layout configuration from react-grid-layout.';
COMMENT ON COLUMN public.dashboard_layouts.created_at IS 'Timestamp when the layout was initially created.';
COMMENT ON COLUMN public.dashboard_layouts.updated_at IS 'Timestamp when the layout was last modified.';

-- 3. Enable Row Level Security (RLS) on the table
-- Important: RLS is crucial for ensuring users can only access their own layouts.
ALTER TABLE public.dashboard_layouts ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS policies
-- Policy: Allow users to select (read) their own layouts
CREATE POLICY "Allow users to select their own layouts"
ON public.dashboard_layouts
FOR SELECT
USING (auth.uid() = user_id);

-- Policy: Allow users to insert layouts for themselves
CREATE POLICY "Allow users to insert their own layouts"
ON public.dashboard_layouts
FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- Policy: Allow users to update their own layouts
CREATE POLICY "Allow users to update their own layouts"
ON public.dashboard_layouts
FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Policy: Allow users to delete their own layouts (Optional, enable if needed)
-- CREATE POLICY "Allow users to delete their own layouts"
-- ON public.dashboard_layouts
-- FOR DELETE
-- USING (auth.uid() = user_id);


-- 5. Create a function to update the updated_at timestamp
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 6. Create a trigger to call the function before any update
CREATE TRIGGER on_dashboard_layouts_updated
BEFORE UPDATE ON public.dashboard_layouts
FOR EACH ROW
EXECUTE FUNCTION public.handle_updated_at();

-- 7. Optional: Add an index for faster lookups by user_id
CREATE INDEX idx_dashboard_layouts_user_id ON public.dashboard_layouts(user_id);

-- 8. Optional: Add a unique constraint if each user should only have one layout *per name*
-- This ensures a user can't have two layouts named 'default', for example.
ALTER TABLE public.dashboard_layouts
ADD CONSTRAINT unique_user_layout_name UNIQUE (user_id, layout_name); 